apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: monitoring
    managedBy: argocd
    managementCodeGroup: chrismlee42
    managementCodeProject: monitoring-config
  name: monitoring
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  sources:
    - path: argocd
      ref: path
      repoURL: https://github.com/chrismlee42/monitoring-config.git
      targetRevision: HEAD
    - chart: grafana
      helm:
        releaseName: grafana
        valuesObject: {}
      ref: helm-grafana
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 10.1.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    #   - ServerSideApply=true
